#+title: Generating a list of links
# Tags #zetteldeft #zd-tutorial #zd-advanced

Backlink: ยง2020-04-27-2358 Advanced Zetteldeft features
See also: ยง2022-09-21-2155 Automated list of links with Org dynamic blocks
   
Working with a Zettelkasten system means creating links to other notes.
This is a crucial activity in order to create meaning and structure within your cloud of notes.

For this purpose, it can be useful to quickly generate a list of notes with a specific search term.
That's what =zetteldeft-insert-list-links= does.
It's best used in combination with =#tags=.

There are two ways to use this feature:
 1. Calling the function *directly*: it prompts for a search term and inserts a list of links to the search results.
    Call =zetteldeft-insert-list-links= and =zetteldeft-list-links-missing= to do so. 
 2. Use an Org-mode source block to generate the list, allowing for basic *automation*.
    Insert such a source block via: =zetteldeft-insert-list-links-block=.
    See ยง2020-04-17-1611 for details.

Sometimes, rather thang simply generating a list, I like to manually link to notes in the text, but then I wonder which notes I /haven't/ linked to yet: I want to find the *missing* links.

That's where =zetteldeft-insert-list-links-missing= comes in.
(Note, however, that once the missing notes have been linked to, they are now part of the current note, which means that calling the function again will not include those notes.)

Final note: to customize how the list entry is formatted, set =zetteldeft-list-prefix= to a string of your choice.

