#+title: Zetteldeft ID and link concepts
# Tags #zd-tutorial #zetteldeft

Backlink: §2020-02-15-1247 Welcome

Each note has a unique *ID*, based on the time and date of its creation.
This note has ID =2020-05-10-1552=.

A note's ID is included in its filename.
IDs are supposed to be stable and shouldn't change.

How IDs are generated is determined by =zetteldeft-id-format=.
They are detected via the regular expression stored in =zetteldeft-id-regex=.
Both are customizable (see §2020-05-13-1815 on customizing Zetteldeft).

Notes contain *links* to other notes.
To identify links, Zetteldeft uses a link indicator, which is =§= by default.
Links thus consist of this symbol and an ID.
And don't worry, you won't have to type the =§= manually.

Even better: the symbol can be modified via =zetteldeft-link-indicator=.
Want to disable it? Set it to an empty string: =""=.

Links can have a =zetteldeft-link-suffix= (but this is disabled by default).
This can be handy if you want to use Zetteldeft for Markdown notes (see §2020-04-17-1532).

A backlink, finally, refers to a link back to another note from which the current note "branches out".
In Zetteldeft, the main course of action is to add a single backlink via a function (see §2020-09-22-0855).
With the power of automated lists of links, it is also possible to easily find all notes that link to the current note (see §2020-08-29-1223).

You can also structure notes with tags: §2021-03-29-2226 Tags in Zetteldeft
